#+title: markuplint.el
#+author: Naoya Yamashita

[[https://github.com/conao3/markuplint.el][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/markuplint.el.png]]

[[https://github.com/conao3/markuplint.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/markuplint.el.svg?style=flat-square]]
[[https://github.com/conao3/markuplint.el/releases][https://img.shields.io/github/tag/conao3/markuplint.el.svg?style=flat-square]]
[[https://github.com/conao3/markuplint.el/actions][https://github.com/conao3/markuplint.el/workflows/Main%20workflow/badge.svg]]

An Emacs interface for [[https://markuplint.dev/][markuplint]], the modern HTML linter that helps you write better markup.

* Overview

[[https://github.com/conao3/markuplint.el][https://raw.githubusercontent.com/conao3/files/master/blob/markuplint.el/markuplint.gif]]

markuplint.el provides Emacs integration with markuplint, enabling you to lint HTML files directly from your editor. It supports both Docker-based and local Node.js installations.

* Requirements

- Emacs 26.1 or later
- markuplint (via Docker or npm)

* Installation

** Using leaf.el

#+begin_src emacs-lisp
(leaf markuplint :ensure t)
#+end_src

** Using use-package

#+begin_src emacs-lisp
(use-package markuplint
  :ensure t)
#+end_src

* Setting Up markuplint

You need markuplint installed to use this package. Choose one of the following methods:

** Option 1: Docker (Recommended for Quick Setup)

Run markuplint via Docker without installing Node.js:

#+begin_src shell
docker run markuplint/markuplint yourfile.html
#+end_src

Set the executable preset in your Emacs configuration:

#+begin_src emacs-lisp
(setq markuplint-executable-preset 'docker)
#+end_src

** Option 2: Local npm Installation

*** Installing Node.js

If you don't have Node.js installed, you can use a version manager like nodenv:

#+begin_src shell
# Install nodenv via anyenv
git clone https://github.com/anyenv/anyenv ~/.anyenv
export PATH="$HOME/.anyenv/bin:$PATH"
eval "$(anyenv init -)"
anyenv install nodenv
nodenv install 20.10.0
nodenv global 20.10.0
#+end_src

*** Installing markuplint

Global installation:

#+begin_src shell
npm install -g markuplint
#+end_src

Or per-project installation:

#+begin_src shell
npm install --save-dev markuplint
#+end_src

*** Verifying the Installation

#+begin_src shell
npx markuplint --version
npx markuplint yourfile.html
#+end_src

Set the executable preset:

#+begin_src emacs-lisp
(setq markuplint-executable-preset 'npx)
#+end_src

* Contributing

Contributions are welcome. Please feel free to submit issues and pull requests.

** Development Setup

Install keg for running tests:

#+begin_src shell
git clone https://github.com/conao3/keg ~/.keg
export PATH="$HOME/.keg/bin:$PATH"
#+end_src

** Workflow

#+begin_src shell
git checkout -b your-feature-branch
# Make your changes
make test
git commit -am "Description of changes"
#+end_src

Then open a pull request on GitHub.

* License

GPLv3. See [[https://github.com/conao3/markuplint.el/blob/master/LICENSE][LICENSE]] for details.

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
